version: '3.9'
services:
  # Сервис для разворачивания контейнера с базой данных
  postgres:
    container_name: postgres
    image: postgres:12
    hostname: database
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=wallet
      - POSTGRES_USER=wallet
      - POSTGRES_PASSWORD=wallet
    ports:
      - "5430:5432"
  # Сервис для разворачивания контейнера с приложением
  webapi:
    build:
      dockerfile: Dockerfile
      context: .
    hostname: webapi
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/wallet
      - POSTGRES_USER=wallet
      - POSTGRES_PASSWORD=wallet
    healthcheck:
      test: curl http://localhost:8080 || exit 0
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 10s
  tests:
    image: wil124/shift-intensiv-winter-2024-tests
    pull_policy: always
    container_name: tests
    ports:
      - "8095:8080"
    depends_on:
      - webapi